sudo: required
dist: trusty
language: java


git:
  submodules: false
before_install: git submodule update --init --recursive

jdk:
- openjdk8
- oraclejdk8
env: GRADLE_OPTS="-Xms1g -Xmx3g"


script: ./gradlew build
notifications:
  email: false

deploy:
  file_glob: true
  provider: releases
  api-key: ${KEY}
  file: "./build/libs/fds-wsapi*.jar"
  skip_cleanup: true
  on:
    tags: true