sudo: required
dist: trusty
language: java
jdk:
- openjdk8
- oraclejdk8
env: GRADLE_OPTS="-Xms1g -Xmx3g"
script: gradle build
notifications:
  email: false

after_success:
  - for f in "./build/libs/fds-wsapi*.jar"; do mv ${f} "./build/libs/fds-wsapi-${TRAVIS_TAG}-${TRAVIS_BUILD_NUMBER}-SNAPSHOT.jar"; done

deploy:
  file_glob: true
  provider: releases
  api-key: ${KEY}
  file: "./build/libs/fds-wsapi*.jar"
  skip_cleanup: true
  on:
    tags: true